export const GET_BODY_PART = 'GET_BODY_PART'
export const GET_ANSWER = 'GET_ANSWER'
export const GET_BMI_DATA = 'GET_BMI_DATA'
export const SEND_ANSWERS = 'SEND_ANSWERS'
export const GET_ALL_ANSWERS = 'GET_ALL_ANSWERS'
export const GET_STORY = 'GET_STORY'
export const CLEAR_ANSWERS = 'CLEAR_ANSWERS'
